spring.datasource.url: jdbc:mysql://localhost:3306/group_chat?useSSL=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: Gaylordsteambath889
spring.jpa.hibernate.ddl-auto: update